Lint fixes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,3 +1,4 @@
+---
 name: Rust Build, Test, and Release
 ### https://github.com/harmless-tech/rust-github-actions
 
@@ -10,7 +11,9 @@ on:
 env:
   bin-name: cargo-prebuilt
   feature-set: '--no-default-features --features default-native'
-  hack-group: '--group-features default,default-native,default-rustls,default-no-tls,rustls,rustls-native-certs,native,vendored-openssl'
+  hack-group: >-
+    --group-features default,default-native,default-rustls,default-no-tls,
+    rustls,rustls-native-certs,native,vendored-openssl
   cache: false
   CARGO_TERM_COLOR: always
 
@@ -32,7 +35,14 @@ jobs:
   publish-crates-io:
     if: ${{ ! contains(github.ref, '-dev') }}
     runs-on: ubuntu-latest
-    needs: [ release, check-fmt, clippy, ink-cross, cross, apple-darwin, pc-windows-msvc ]
+    needs:
+      - release
+      - check-fmt
+      - clippy
+      - ink-cross
+      - cross
+      - apple-darwin
+      - pc-windows-msvc
     steps:
       - uses: actions/checkout@v4
       - name: Update Rust
@@ -40,13 +50,20 @@ jobs:
           rustup update
           rustc --version
       - name: Publish
-        run: cargo publish --verbose --locked --token ${CRATES_TOKEN}
+        run: cargo publish --verbose --locked --token "${CRATES_TOKEN}"
         env:
           CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
 
   publish-github-releases:
     runs-on: ubuntu-latest
-    needs: [ release, check-fmt, clippy, ink-cross, cross, apple-darwin, pc-windows-msvc ]
+    needs:
+      - release
+      - check-fmt
+      - clippy
+      - ink-cross
+      - cross
+      - apple-darwin
+      - pc-windows-msvc
     steps:
       - uses: actions/checkout@v4
       - uses: actions/download-artifact@v4
@@ -59,7 +76,7 @@ jobs:
             if [ -d "${D}" ]; then
               echo "${D}"
               pushd "${D}"
-              cat *.sha256 >> ../hashes.sha256
+              cat ./*.sha256 >> ../hashes.sha256
               popd
             fi
           done
@@ -77,8 +94,8 @@ jobs:
         
               for file in ./*.tar.gz ./*.zip; do
                 if [ -f "$file" ]; then
-                  minisign -S -s ~/.minisign_secret.key -m $file
-                  minisign -V -p ../keys/cargo-prebuilt.pub -m $file
+                  minisign -S -s ~/.minisign_secret.key -m "$file"
+                  minisign -V -p ../keys/cargo-prebuilt.pub -m "$file"
                 fi 
               done
                 
@@ -112,14 +129,16 @@ jobs:
           cargo +nightly fmt --check 2>&1 | tee .step-data.txt
       - name: Put into summary (success)
         if: success()
-        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+        run: echo "Success" >> "$GITHUB_STEP_SUMMARY"
       - name: Put into summary (failure)
         if: failure()
         run: |
-          echo "Failed!" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          {
+            echo "Failed!"
+            echo "\`\`\`shell"
+            cat .step-data.txt
+            echo "\`\`\`"
+          } >> "$GITHUB_STEP_SUMMARY"
 
   clippy:
     strategy:
@@ -147,20 +166,24 @@ jobs:
         shell: bash
         run: |
           set -o pipefail
-          cargo clippy --all-targets --verbose --workspace --release --locked -- -D warnings 2>&1 | tee .step-data.txt
-          cargo clippy --all-targets --verbose --workspace --release --locked ${{ env.feature-set }} -- -D warnings 2>&1 | tee .step-data.txt
+          cargo clippy --all-targets --verbose --workspace --release --locked \
+          -- -D warnings 2>&1 | tee .step-data.txt
+          cargo clippy --all-targets --verbose --workspace --release --locked \
+          ${{ env.feature-set }} -- -D warnings 2>&1 | tee .step-data.txt
       - name: Put into summary (success)
         if: success()
         shell: bash
-        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+        run: echo "Success" >> "$GITHUB_STEP_SUMMARY"
       - name: Put into summary (failure)
         if: failure()
         shell: bash
         run: |
-          echo "Failed!" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          {
+            echo "Failed!"
+            echo "\`\`\`shell"
+            cat .step-data.txt
+            echo "\`\`\`"
+          } >> "$GITHUB_STEP_SUMMARY"
 
   cargo-hack:
     strategy:
@@ -191,24 +214,29 @@ jobs:
         shell: bash
         run: |
           set -o pipefail
-          cargo hack check --each-feature --no-dev-deps --verbose --workspace --release --locked 2>&1 | tee .step-data.txt
+          cargo hack check --each-feature --no-dev-deps --verbose --workspace \
+          --release --locked 2>&1 | tee .step-data.txt
       - name: Hack Check (feature-powerset)
         shell: bash
         run: |
           set -o pipefail
-          cargo hack check --feature-powerset ${{ env.hack-group }} --no-dev-deps --verbose --workspace --release --locked 2>&1 | tee .step-data.txt
+          cargo hack check --feature-powerset ${{ env.hack-group }} \
+          --no-dev-deps --verbose --workspace --release \
+          --locked 2>&1 | tee .step-data.txt
       - name: Put into summary (success)
         if: success()
         shell: bash
-        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+        run: echo "Success" >> "$GITHUB_STEP_SUMMARY"
       - name: Put into summary (failure)
         if: failure()
         shell: bash
         run: |
-          echo "Failed!" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          {
+            echo "Failed!"
+            echo "\`\`\`shell"
+            cat .step-data.txt
+            echo "\`\`\`"
+          } >> "$GITHUB_STEP_SUMMARY"
 
   cargo-msrv:
     strategy:
@@ -241,19 +269,22 @@ jobs:
         shell: bash
         run: |
           set -o pipefail
-          cargo msrv verify -- cargo check --verbose --release --locked 2>&1 | tee .step-data.txt
+          cargo msrv verify -- cargo check --verbose --release \
+          --locked 2>&1 | tee .step-data.txt
       - name: Put into summary (success)
         if: success()
         shell: bash
-        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+        run: echo "Success" >> "$GITHUB_STEP_SUMMARY"
       - name: Put into summary (failure)
         if: failure()
         shell: bash
         run: |
-          echo "Failed!" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          {
+            echo "Failed!"
+            echo "\`\`\`shell"
+            cat .step-data.txt
+            echo "\`\`\`"
+          } >> "$GITHUB_STEP_SUMMARY"
 
   cargo-deny:
     env:
@@ -276,15 +307,17 @@ jobs:
       - name: Put into summary (success)
         if: success()
         shell: bash
-        run: echo "Success" >> $GITHUB_STEP_SUMMARY
+        run: echo "Success" >> "$GITHUB_STEP_SUMMARY"
       - name: Put into summary (failure)
         if: failure()
         shell: bash
         run: |
-          echo "Failed!" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`shell" >> $GITHUB_STEP_SUMMARY
-          cat .step-data.txt >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          {
+            echo "Failed!"
+            echo "\`\`\`shell"
+            cat .step-data.txt
+            echo "\`\`\`"
+          } >> "$GITHUB_STEP_SUMMARY"
 
   reports:
     runs-on: ubuntu-latest
@@ -308,18 +341,22 @@ jobs:
       - name: Deps Report
         run: |
           test -f Cargo.lock || cargo generate-lockfile --verbose
-          echo "### Deps:" >> $GITHUB_STEP_SUMMARY
-          echo "Generated on: $(date --utc)" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-          cargo tree --verbose -e normal,build --locked >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          {
+            echo "### Deps:"
+            echo "Generated on: $(date --utc)"
+            echo "\`\`\`"
+            cargo tree --verbose -e normal,build --locked
+            echo "\`\`\`"
+          } >> "$GITHUB_STEP_SUMMARY"
       - name: Audit Report
         run: |
-          echo "### Audit:" >> $GITHUB_STEP_SUMMARY
-          echo "Generated on: $(date --utc)" >> $GITHUB_STEP_SUMMARY
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-          cargo audit >> $GITHUB_STEP_SUMMARY || true
-          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          {
+            echo "### Audit:"
+            echo "Generated on: $(date --utc)"
+            echo "\`\`\`"
+          } >> "$GITHUB_STEP_SUMMARY"
+          cargo audit >> "$GITHUB_STEP_SUMMARY" || true
+          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
 
   ink-cross:
     strategy:
@@ -345,7 +382,7 @@ jobs:
           - target: x86_64-unknown-linux-musl
             can-test: true
     runs-on: ubuntu-latest
-    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
+    needs: [check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny]
     steps:
       - uses: actions/checkout@v4
       - uses: cargo-prebuilt/cargo-prebuilt-action@v3
@@ -357,28 +394,34 @@ jobs:
         if: ${{ matrix.can-test }}
         run: |
           docker run --rm \
-          --userns host --user $(id -u):$(id -g) \
-          -v $HOME/.cargo/registry:/usr/local/cargo/registry \
+          --userns host --user "$(id -u)":"$(id -g)" \
+          -v "$HOME"/.cargo/registry:/usr/local/cargo/registry \
           -v ./:/project \
           ghcr.io/cargo-prebuilt/ink-cross:stable-${{ matrix.target }} \
-          test --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+          test --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Build
         run: |
           docker run --rm \
-          --userns host --user $(id -u):$(id -g) \
-          -v $HOME/.cargo/registry:/usr/local/cargo/registry \
+          --userns host --user "$(id -u)":"$(id -g)" \
+          -v "$HOME"/.cargo/registry:/usr/local/cargo/registry \
           -v ./:/project \
           ghcr.io/cargo-prebuilt/ink-cross:stable-${{ matrix.target }} \
-          auditable build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+          auditable build --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Run cargo-prebuilt
         if: ${{ matrix.can-test }}
         run: |
           target/${{ matrix.target }}/release/${{ env.bin-name }} just
           just --version
       - name: Tar
-        run: tar czvf ${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
+        run: |
+          tar czvf ${{ matrix.target }}.tar.gz \
+          -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
       - name: Hash
-        run: echo "$(coreutils sha256sum ${{ matrix.target }}.tar.gz)" > ${{ matrix.target }}.sha256
+        run: |
+          coreutils sha256sum ${{ matrix.target }}.tar.gz \
+          > ${{ matrix.target }}.sha256
       - name: Artifact
         uses: actions/upload-artifact@v4
         with:
@@ -401,7 +444,7 @@ jobs:
           - target: powerpc64-unknown-linux-gnu
             can-test: true
     runs-on: ubuntu-latest
-    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
+    needs: [check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny]
     steps:
       - uses: actions/checkout@v4
       - name: Update Rust and add target
@@ -416,13 +459,21 @@ jobs:
         if: ${{ env.cache == 'true' }}
       - name: Run tests
         if: ${{ matrix.can-test }}
-        run: cross test --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+        run: |
+          cross test --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Build
-        run: cross build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+        run: |
+          cross build --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Tar
-        run: tar czvf ${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
+        run: |
+          tar czvf ${{ matrix.target }}.tar.gz \
+          -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
       - name: Hash
-        run: echo "$(coreutils sha256sum ${{ matrix.target }}.tar.gz)" > ${{ matrix.target }}.sha256
+        run: |
+          coreutils sha256sum ${{ matrix.target }}.tar.gz \
+          > ${{ matrix.target }}.sha256
       - name: Artifact
         uses: actions/upload-artifact@v4
         with:
@@ -441,7 +492,7 @@ jobs:
           - target: aarch64-apple-darwin
             os: macos-14
     runs-on: ${{ matrix.os }}
-    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
+    needs: [check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny]
     steps:
       - uses: actions/checkout@v4
       - name: Update Rust and add target
@@ -455,17 +506,25 @@ jobs:
       - uses: Swatinem/rust-cache@v2
         if: ${{ env.cache == 'true' }}
       - name: Run tests
-        run: cargo test --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+        run: |
+          cargo test --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Build
-        run: cargo auditable build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+        run: |
+          cargo auditable build --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Run cargo-prebuilt
         run: |
           target/${{ matrix.target }}/release/${{ env.bin-name }} just
           just --version
       - name: Tar
-        run: tar czvf ${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
+        run: |
+          tar czvf ${{ matrix.target }}.tar.gz \
+          -C ./target/${{ matrix.target }}/release ${{ env.bin-name }}
       - name: Hash
-        run: echo "$(coreutils sha256sum ${{ matrix.target }}.tar.gz)" > ${{ matrix.target }}.sha256
+        run: |
+          coreutils sha256sum ${{ matrix.target }}.tar.gz \
+          > ${{ matrix.target }}.sha256
       - name: Artifact
         uses: actions/upload-artifact@v4
         with:
@@ -484,7 +543,7 @@ jobs:
           - target: aarch64-pc-windows-msvc
             can-test: false
     runs-on: windows-latest
-    needs: [ check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny ]
+    needs: [check-fmt, clippy, cargo-hack, cargo-msrv, cargo-deny]
     steps:
       - uses: actions/checkout@v4
       - name: Update Rust and add target
@@ -499,9 +558,13 @@ jobs:
         if: ${{ env.cache == 'true' }}
       - name: Run tests
         if: ${{ matrix.can-test }}
-        run: cargo test --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+        run: |
+          cargo test --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Build
-        run: cargo auditable build --verbose --workspace --release --locked --target ${{ matrix.target }} ${{ env.feature-set }}
+        run: |
+          cargo auditable build --verbose --workspace --release --locked \
+          --target ${{ matrix.target }} ${{ env.feature-set }}
       - name: Run cargo-prebuilt
         if: ${{ matrix.can-test }}
         run: |
@@ -512,7 +575,9 @@ jobs:
           cd target/${{ matrix.target }}/release
           7z a -tzip ../../../${{ matrix.target }}.zip ${{ env.bin-name }}.exe
       - name: Hash
-        run: echo "$(coreutils sha256sum ${{ matrix.target }}.zip)" > ${{ matrix.target }}.sha256
+        run: |
+          coreutils sha256sum ${{ matrix.target }}.zip \
+          > ${{ matrix.target }}.sha256
       - name: Artifact
         uses: actions/upload-artifact@v4
         with:
